name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare to install ARM dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo sed -i 's/^deb /deb [arch=amd64] /g' /etc/apt/sources.list
          cat .github/sources.list | sudo tee -a /etc/apt/sources.list
          sudo apt update

      - name: Install ARM dependencies
        run: > 
          sudo apt-get install -y
          gcc-aarch64-linux-gnu
          libwebkit2gtk-4.1-dev:arm64
          libssl-dev:arm64
          libayatana-appindicator3-dev:arm64
          librsvg2-dev:arm64
          libxdo-dev:arm64
          libgtk-3-dev
          libjavascriptcoregtk-4.1-dev:arm64
          libsoup-3.0-dev:arm64
          pkg-config:arm64
          libudev-dev:arm64
          librust-openssl-sys-dev:arm64
          perl

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install frontend dependencies
        run: npm ci
        
      - uses: tauri-apps/tauri-action@v0
        env:
          PKG_CONFIG_SYSROOT_DIR: /usr/aarch64-linux-gnu/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: last-snow-v__VERSION__
          releaseName: 'Last Snow Input v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: --target aarch64-unknown-linux-gnu
