name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    env:
      APT_CACHE_VERSION: 1
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo sed -i 's/^deb /deb [arch=amd64] /g' /etc/apt/sources.list
          cat .github/sources.list | sudo tee -a /etc/apt/sources.list

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >
            libgtk-3-dev
            libwebkit2gtk-4.0-dev
            libayatana-appindicator3-dev
            librsvg2-dev
            gcc-aarch64-linux-gnu
            libwebkit2gtk-4.0-dev:arm64
            libssl-dev:arm64 
          version: ${{ env.APT_CACHE_VERSION }}
          execute_install_scripts: true

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build binary
        run: |
          cd src-tauri
          cargo build --release --target aarch64-unknown-linux-gnu
          cd ..
        env:
          PKG_CONFIG_SYSROOT_DIR: /usr/aarch64-linux-gnu/

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: last-snow-${{ github.ref }}
          path: "src-tauri/target/**/*.deb"

